-- sql/raw/001_create_raw_tables.sql
-- Generado automáticamente desde docs/db_model/raw_inventory/*.tsv.
-- No editar manualmente salvo que se regenere desde los inventarios.

CREATE SCHEMA IF NOT EXISTS raw;

CREATE TABLE IF NOT EXISTS raw.blood_data (
    blood_data_id integer NOT NULL,
    pat_visit_id integer NOT NULL,
    effort_type_id smallint NOT NULL,
    effort_time timestamp without time zone NOT NULL,
    effort_cd_us double precision NOT NULL,
    effort_artificial boolean NOT NULL,
    effort_selected boolean NOT NULL,
    fio2 double precision NOT NULL,
    pa_o2 double precision NOT NULL,
    pa_co2 double precision NOT NULL,
    p_h double precision NOT NULL,
    hgb double precision NOT NULL,
    base_excess double precision NOT NULL,
    cv_o2 double precision NOT NULL,
    p_aa_o2 double precision NOT NULL,
    met_hb double precision NOT NULL,
    co_hb double precision NOT NULL,
    temperature double precision NOT NULL,
    sa_o2 double precision NOT NULL,
    qsp_qt double precision NOT NULL,
    hco3 double precision NOT NULL,
    pao2_alv double precision NOT NULL,
    hct double precision NOT NULL,
    cva_co2 double precision NOT NULL,
    hgb_fx double precision NOT NULL,
    cav_o2 double precision NOT NULL,
    pav_o2 double precision NOT NULL,
    pv_co2 double precision NOT NULL,
    vp_h double precision NOT NULL,
    cv_p double precision NOT NULL,
    pv_o2 double precision NOT NULL,
    lactate double precision NOT NULL,
    ca_o2 double precision NOT NULL,
    sv_o2 double precision NOT NULL,
    sup_o2_device varchar(20),
    qsp_qt_manually_entered boolean NOT NULL,
    cv_o2_manually_entered boolean NOT NULL,
    pao2_manually_entered boolean NOT NULL,
    base_excess_manually_entered boolean NOT NULL,
    hco3_manually_entered boolean NOT NULL,
    sa_o2_manually_entered boolean NOT NULL,
    sv_o2_manually_entered boolean NOT NULL,
    pf_protocol_stage_index smallint NOT NULL,
    hgb_gm_l double precision NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (blood_data_id)
);

CREATE TABLE IF NOT EXISTS raw.dlco_data (
    dlco_data_id integer NOT NULL,
    pat_visit_id integer NOT NULL,
    effort_type_id smallint NOT NULL,
    effort_time timestamp without time zone NOT NULL,
    effort_cd_us double precision NOT NULL,
    effort_artificial boolean NOT NULL,
    effort_manual boolean NOT NULL,
    effort_selected boolean NOT NULL,
    dlc_ounc double precision NOT NULL,
    dlc_ocor double precision NOT NULL,
    dm double precision NOT NULL,
    kco double precision NOT NULL,
    va double precision NOT NULL,
    dlva double precision NOT NULL,
    svcsb double precision NOT NULL,
    frcsb double precision NOT NULL,
    rvsb double precision NOT NULL,
    ervsb double precision NOT NULL,
    tlcsb double precision NOT NULL,
    rvtlcsb double precision NOT NULL,
    tau double precision NOT NULL,
    dlcosvc_source_data bytea,
    dlco_gas_source_data bytea,
    effort_rp_lp boolean NOT NULL,
    fi_ne double precision NOT NULL,
    fe_ne double precision NOT NULL,
    fi_co double precision NOT NULL,
    fe_co double precision NOT NULL,
    bht double precision NOT NULL,
    ivc double precision NOT NULL,
    dlcoats_codes varchar(10),
    collection_protocol smallint NOT NULL,
    start_collect_vol double precision NOT NULL,
    stop_collect_vol double precision NOT NULL,
    mouth_pressure_error boolean NOT NULL,
    pf_protocol_stage_index smallint NOT NULL,
    ictlcsb double precision NOT NULL,
    fi_ch4 double precision NOT NULL,
    fe_ch4 double precision NOT NULL,
    fi_c2_h2 double precision NOT NULL,
    fe_c2_h2 double precision NOT NULL,
    dlco_real_time_source_data bytea,
    ch4_slope double precision NOT NULL,
    anatomic_deadspace double precision NOT NULL,
    valve_deadspace double precision NOT NULL,
    pre_analysis_trace_data bytea,
    vatlcpl double precision NOT NULL,
    vatlcn2 double precision NOT NULL,
    dlcoats_grades varchar(10),
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (dlco_data_id)
);

CREATE TABLE IF NOT EXISTS raw.delta_co2_data (
    delta_co2_data_id integer NOT NULL,
    pat_visit_id integer NOT NULL,
    effort_type_id smallint NOT NULL,
    effort_time timestamp without time zone NOT NULL,
    effort_cd_us double precision NOT NULL,
    effort_artificial boolean NOT NULL,
    effort_manual boolean NOT NULL,
    effort_selected boolean NOT NULL,
    effort_rp_lp boolean NOT NULL,
    pf_protocol_stage_index smallint NOT NULL,
    vt double precision NOT NULL,
    vd double precision NOT NULL,
    vd_vt double precision NOT NULL,
    frc double precision NOT NULL,
    rr double precision NOT NULL,
    d_phase3 double precision NOT NULL,
    ti double precision NOT NULL,
    te double precision NOT NULL,
    ttot double precision NOT NULL,
    delta_co2_source_data bytea,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (delta_co2_data_id)
);

CREATE TABLE IF NOT EXISTS raw.dynamic_data (
    dynamic_data_id integer NOT NULL,
    pat_visit_id integer NOT NULL,
    effort_type_id smallint NOT NULL,
    effort_time timestamp without time zone NOT NULL,
    effort_cd_us double precision NOT NULL,
    effort_artificial boolean NOT NULL,
    effort_manual boolean NOT NULL,
    effort_selected boolean NOT NULL,
    rr_dyn double precision NOT NULL,
    tv_dyn double precision NOT NULL,
    cdyn double precision NOT NULL,
    cdyn_cst double precision NOT NULL,
    rp_i_dyn double precision NOT NULL,
    rp_e_dyn double precision NOT NULL,
    rp_dyn double precision NOT NULL,
    dynamic_source_data bytea,
    pf_protocol_stage_index smallint NOT NULL,
    effort_rp_lp boolean NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (dynamic_data_id)
);

CREATE TABLE IF NOT EXISTS raw.effort_type (
    effort_type_id smallint NOT NULL,
    effort_type_desc varchar(30),
    effort_type_note varchar(50),
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (effort_type_id)
);

CREATE TABLE IF NOT EXISTS raw.fot_data (
    fot_data_id integer NOT NULL,
    pat_visit_id integer NOT NULL,
    effort_type_id smallint NOT NULL,
    effort_time timestamp without time zone NOT NULL,
    effort_cd_us double precision NOT NULL,
    effort_selected boolean NOT NULL,
    effort_artificial boolean NOT NULL,
    effort_manual boolean NOT NULL,
    effort_rp_lp boolean NOT NULL,
    pf_protocol_stage_index smallint NOT NULL,
    stimulating_freq_id smallint NOT NULL,
    duration smallint NOT NULL,
    number_of_breaths integer NOT NULL,
    flow_limitation_breaths integer NOT NULL,
    percent_accepted_breaths double precision NOT NULL,
    resonant_freq double precision NOT NULL,
    r5 double precision NOT NULL,
    x5 double precision NOT NULL,
    coherence5 double precision NOT NULL,
    r7 double precision NOT NULL,
    x7 double precision NOT NULL,
    coherence7 double precision NOT NULL,
    r11 double precision NOT NULL,
    x11 double precision NOT NULL,
    coherence11 double precision NOT NULL,
    r13 double precision NOT NULL,
    x13 double precision NOT NULL,
    coherence13 double precision NOT NULL,
    r17 double precision NOT NULL,
    x17 double precision NOT NULL,
    coherence17 double precision NOT NULL,
    r19 double precision NOT NULL,
    x19 double precision NOT NULL,
    coherence19 double precision NOT NULL,
    r23 double precision NOT NULL,
    x23 double precision NOT NULL,
    coherence23 double precision NOT NULL,
    r29 double precision NOT NULL,
    x29 double precision NOT NULL,
    coherence29 double precision NOT NULL,
    r31 double precision NOT NULL,
    x31 double precision NOT NULL,
    coherence31 double precision NOT NULL,
    r37 double precision NOT NULL,
    x37 double precision NOT NULL,
    coherence37 double precision NOT NULL,
    expiratory_reactance double precision NOT NULL,
    inspiratory_conductance_mean double precision NOT NULL,
    r_insp5_hz double precision NOT NULL,
    r_exp5_hz double precision NOT NULL,
    r_total5_hz double precision NOT NULL,
    x_insp5_hz double precision NOT NULL,
    x_exp5_hz double precision NOT NULL,
    x_total5_hz double precision NOT NULL,
    r_insp5_hz_sd double precision NOT NULL,
    r_exp5_hz_sd double precision NOT NULL,
    r_total5_hz_sd double precision NOT NULL,
    x_insp5_hz_sd double precision NOT NULL,
    x_exp5_hz_sd double precision NOT NULL,
    x_total5_hz_sd double precision NOT NULL,
    r_insp6_hz double precision NOT NULL,
    r_exp6_hz double precision NOT NULL,
    r_total6_hz double precision NOT NULL,
    x_insp6_hz double precision NOT NULL,
    x_exp6_hz double precision NOT NULL,
    x_total6_hz double precision NOT NULL,
    r_insp6_hz_sd double precision NOT NULL,
    r_exp6_hz_sd double precision NOT NULL,
    r_total6_hz_sd double precision NOT NULL,
    x_insp6_hz_sd double precision NOT NULL,
    x_exp6_hz_sd double precision NOT NULL,
    x_total6_hz_sd double precision NOT NULL,
    r_insp8_hz double precision NOT NULL,
    r_exp8_hz double precision NOT NULL,
    r_total8_hz double precision NOT NULL,
    x_insp8_hz double precision NOT NULL,
    x_exp8_hz double precision NOT NULL,
    x_total8_hz double precision NOT NULL,
    r_insp8_hz_sd double precision NOT NULL,
    r_exp8_hz_sd double precision NOT NULL,
    r_total8_hz_sd double precision NOT NULL,
    x_insp8_hz_sd double precision NOT NULL,
    x_exp8_hz_sd double precision NOT NULL,
    x_total8_hz_sd double precision NOT NULL,
    r_insp10_hz double precision NOT NULL,
    r_exp10_hz double precision NOT NULL,
    r_total10_hz double precision NOT NULL,
    x_insp10_hz double precision NOT NULL,
    x_exp10_hz double precision NOT NULL,
    x_total10_hz double precision NOT NULL,
    r_insp10_hz_sd double precision NOT NULL,
    r_exp10_hz_sd double precision NOT NULL,
    r_total10_hz_sd double precision NOT NULL,
    x_insp10_hz_sd double precision NOT NULL,
    x_exp10_hz_sd double precision NOT NULL,
    x_total10_hz_sd double precision NOT NULL,
    r_insp11_hz double precision NOT NULL,
    r_exp11_hz double precision NOT NULL,
    r_total11_hz double precision NOT NULL,
    x_insp11_hz double precision NOT NULL,
    x_exp11_hz double precision NOT NULL,
    x_total11_hz double precision NOT NULL,
    r_insp11_hz_sd double precision NOT NULL,
    r_exp11_hz_sd double precision NOT NULL,
    r_total11_hz_sd double precision NOT NULL,
    x_insp11_hz_sd double precision NOT NULL,
    x_exp11_hz_sd double precision NOT NULL,
    x_total11_hz_sd double precision NOT NULL,
    r_insp19_hz double precision NOT NULL,
    r_exp19_hz double precision NOT NULL,
    r_total19_hz double precision NOT NULL,
    x_insp19_hz double precision NOT NULL,
    x_exp19_hz double precision NOT NULL,
    x_total19_hz double precision NOT NULL,
    r_insp19_hz_sd double precision NOT NULL,
    r_exp19_hz_sd double precision NOT NULL,
    r_total19_hz_sd double precision NOT NULL,
    x_insp19_hz_sd double precision NOT NULL,
    x_exp19_hz_sd double precision NOT NULL,
    x_total19_hz_sd double precision NOT NULL,
    inspiratory_flow_mean double precision NOT NULL,
    inspiratory_flow_std_dev double precision NOT NULL,
    expiratory_flow_mean double precision NOT NULL,
    expiratory_flow_std_dev double precision NOT NULL,
    ttot_mean double precision NOT NULL,
    ttot_std_dev double precision NOT NULL,
    ti_mean double precision NOT NULL,
    ti_std_dev double precision NOT NULL,
    te_mean double precision NOT NULL,
    te_std_dev double precision NOT NULL,
    respiratory_rate_mean double precision NOT NULL,
    respiratory_rate_std_dev double precision NOT NULL,
    ti_ttot_mean double precision NOT NULL,
    ti_ttot_std_dev double precision NOT NULL,
    tidal_volume_mean double precision NOT NULL,
    tidal_volume_std_dev double precision NOT NULL,
    ventilation_mean double precision NOT NULL,
    ventilation_std_dev double precision NOT NULL,
    efl_xrs_mean double precision NOT NULL,
    efl_xrs_std_dev double precision NOT NULL,
    r519_mean double precision NOT NULL,
    r519_std_dev double precision NOT NULL,
    real_time_source_data bytea,
    avg_breath_source_data bytea,
    accepted_breaths_source_data bytea,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (fot_data_id)
);

CREATE TABLE IF NOT EXISTS raw.frc_data (
    frc_data_id integer NOT NULL,
    pat_visit_id integer NOT NULL,
    effort_type_id smallint NOT NULL,
    effort_time timestamp without time zone NOT NULL,
    effort_cd_us double precision NOT NULL,
    effort_artificial boolean NOT NULL,
    effort_manual boolean NOT NULL,
    effort_selected boolean NOT NULL,
    frcn2 double precision NOT NULL,
    rvn2 double precision NOT NULL,
    tlcn2 double precision NOT NULL,
    rvtlcn2 double precision NOT NULL,
    v_dan_n2 double precision NOT NULL,
    wash_time double precision NOT NULL,
    final_n2 double precision NOT NULL,
    clear_index double precision NOT NULL,
    frc_source_data bytea,
    effort_rp_lp boolean NOT NULL,
    switch_in_error double precision NOT NULL,
    frcats_codes varchar(10),
    frcsvc_source_data bytea,
    pf_protocol_stage_index smallint NOT NULL,
    external_deadspace double precision NOT NULL,
    ictlcn2 double precision NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (frc_data_id)
);

CREATE TABLE IF NOT EXISTS raw.fvl_data (
    fvl_data_id integer NOT NULL,
    pat_visit_id integer NOT NULL,
    effort_type_id smallint NOT NULL,
    effort_time timestamp without time zone NOT NULL,
    effort_cd_us double precision NOT NULL,
    effort_artificial boolean NOT NULL,
    effort_manual boolean NOT NULL,
    effort_selected boolean NOT NULL,
    fvc double precision NOT NULL,
    fev05 double precision NOT NULL,
    fev1 double precision NOT NULL,
    fev2 double precision NOT NULL,
    fev3 double precision NOT NULL,
    fev6 double precision NOT NULL,
    fev7 double precision NOT NULL,
    fev10 double precision NOT NULL,
    fev05_fvc double precision NOT NULL,
    fev1_fvc double precision NOT NULL,
    fev2_fvc double precision NOT NULL,
    fev3_fvc double precision NOT NULL,
    fev6_fvc double precision NOT NULL,
    fef10 double precision NOT NULL,
    fef25 double precision NOT NULL,
    fef40 double precision NOT NULL,
    fef50 double precision NOT NULL,
    fef60 double precision NOT NULL,
    fef70 double precision NOT NULL,
    fef75 double precision NOT NULL,
    fef80 double precision NOT NULL,
    fef85 double precision NOT NULL,
    fef90 double precision NOT NULL,
    fef_max double precision NOT NULL,
    fef2575 double precision NOT NULL,
    fef7585 double precision NOT NULL,
    fef2001200 double precision NOT NULL,
    exp_time double precision NOT NULL,
    fet2575 double precision NOT NULL,
    fivc double precision NOT NULL,
    fiv1 double precision NOT NULL,
    fiv1_fivc double precision NOT NULL,
    fif25 double precision NOT NULL,
    fif50 double precision NOT NULL,
    fif75 double precision NOT NULL,
    fif2575 double precision NOT NULL,
    fif_max double precision NOT NULL,
    fef50_fif50 double precision NOT NULL,
    to_fef_max double precision NOT NULL,
    vol_extrap double precision NOT NULL,
    mmet double precision NOT NULL,
    fvc_mean_tr double precision NOT NULL,
    fev1_svc double precision NOT NULL,
    p_alv_peak double precision NOT NULL,
    vol_p_alv_pk double precision NOT NULL,
    fvl_inspiratory_source_data bytea,
    fvl_expiratory_source_data bytea,
    fvl_tidal_source_data bytea,
    fvlats_codes varchar(10),
    effort_rp_lp boolean NOT NULL,
    fef_max_fvc double precision NOT NULL,
    fev1_fev6 double precision NOT NULL,
    fev05_fev6 double precision NOT NULL,
    fev2_fev6 double precision NOT NULL,
    fev3_fev6 double precision NOT NULL,
    fef_max_fev6 double precision NOT NULL,
    pf_protocol_stage_index smallint NOT NULL,
    pef double precision NOT NULL,
    v_max60 double precision NOT NULL,
    v_max70 double precision NOT NULL,
    v_max80 double precision NOT NULL,
    mp30 double precision NOT NULL,
    fef50_fvc double precision NOT NULL,
    fef75_fvc double precision NOT NULL,
    fvl_volume_time_source_data bytea,
    jaeger_effort boolean NOT NULL,
    fev075 double precision NOT NULL,
    test_grade_nlhep varchar(1),
    test_grade_ats varchar(10),
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (fvl_data_id)
);

CREATE TABLE IF NOT EXISTS raw.hardware (
    hardware_id smallint NOT NULL,
    hardware_desc varchar(25) NOT NULL,
    spirometry boolean NOT NULL,
    frc boolean NOT NULL,
    pleth boolean NOT NULL,
    dlco boolean NOT NULL,
    sbn2 boolean NOT NULL,
    gx boolean NOT NULL,
    mip_mep boolean NOT NULL,
    compliance boolean NOT NULL,
    p100 boolean NOT NULL,
    pre_line_flush_time integer NOT NULL,
    relieve_time integer NOT NULL,
    flush_line_time_on_entry integer NOT NULL,
    valve_delay integer NOT NULL,
    empty_chamber_time integer NOT NULL,
    valve_dead_space double precision NOT NULL,
    mouth_delay_samples smallint NOT NULL,
    box_delay_samples smallint NOT NULL,
    flow_delay_samples smallint NOT NULL,
    box_cal_pump_volume integer NOT NULL,
    n2_wash_corr_factor_human double precision NOT NULL,
    n2_wash_corr_factor_syringe double precision NOT NULL,
    delta_co2 boolean NOT NULL,
    fot boolean NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (hardware_id)
);

CREATE TABLE IF NOT EXISTS raw.mvv_data (
    mvv_data_id integer NOT NULL,
    pat_visit_id integer NOT NULL,
    effort_type_id smallint NOT NULL,
    effort_time timestamp without time zone NOT NULL,
    effort_cd_us double precision NOT NULL,
    effort_artificial boolean NOT NULL,
    effort_manual boolean NOT NULL,
    effort_selected boolean NOT NULL,
    mvv double precision NOT NULL,
    rrmvv double precision NOT NULL,
    tvmvv double precision NOT NULL,
    mvv_source_data bytea,
    pf_protocol_stage_index smallint NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (mvv_data_id)
);

CREATE TABLE IF NOT EXISTS raw.mip_data (
    mip_data_id integer NOT NULL,
    pat_visit_id integer NOT NULL,
    effort_type_id smallint NOT NULL,
    effort_time timestamp without time zone NOT NULL,
    effort_cd_us double precision NOT NULL,
    effort_artificial boolean NOT NULL,
    effort_manual boolean NOT NULL,
    effort_selected boolean NOT NULL,
    mep double precision NOT NULL,
    mip double precision NOT NULL,
    mip_source_data bytea,
    pf_protocol_stage_index smallint NOT NULL,
    percent_tlc double precision NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (mip_data_id)
);

CREATE TABLE IF NOT EXISTS raw.p100_data (
    p100_data_id integer NOT NULL,
    pat_visit_id integer NOT NULL,
    effort_selected boolean NOT NULL,
    effort_time timestamp without time zone NOT NULL,
    effort_type_id smallint NOT NULL,
    effort_rp_lp boolean NOT NULL,
    effort_manual boolean NOT NULL,
    effort_artificial boolean NOT NULL,
    effort_cd_us double precision NOT NULL,
    rr double precision NOT NULL,
    vt double precision NOT NULL,
    ve double precision NOT NULL,
    pocc double precision NOT NULL,
    p100_source_data bytea,
    pf_protocol_stage_index smallint NOT NULL,
    pet_co2 double precision NOT NULL,
    spo2 double precision NOT NULL,
    fio2 double precision NOT NULL,
    ti_ttot double precision NOT NULL,
    vt_ti double precision NOT NULL,
    f_vt double precision NOT NULL,
    p_fx_test boolean NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (p100_data_id)
);

CREATE TABLE IF NOT EXISTS raw.pf_protocol (
    pf_protocol_name varchar(30) NOT NULL,
    challenge_agent_id smallint NOT NULL,
    pf_protocol_is_default boolean NOT NULL,
    pf_protocol_guid uuid NOT NULL,
    pf_protocol_deleted boolean NOT NULL,
    study_guid uuid,
    use_pd_level1 boolean NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (pf_protocol_guid)
);

CREATE TABLE IF NOT EXISTS raw.pf_protocol_stage (
    pf_protocol_stage_id integer NOT NULL,
    pf_protocol_stage_label varchar(15) NOT NULL,
    pf_protocol_stage_concentration double precision NOT NULL,
    pf_protocol_stage_index smallint NOT NULL,
    pf_protocol_stage_comment varchar(60),
    pf_protocol_guid uuid NOT NULL,
    pf_protocol_stage_delivered_dose double precision NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (pf_protocol_stage_id)
);

CREATE TABLE IF NOT EXISTS raw.pat_visit (
    pat_visit_id integer NOT NULL,
    dyspnea_id smallint NOT NULL,
    cough_id smallint NOT NULL,
    wheeze_id smallint NOT NULL,
    tobacco_id smallint NOT NULL,
    visit_date_time timestamp without time zone NOT NULL,
    review_status_id smallint NOT NULL,
    account varchar(20),
    visit_aux_data varchar(50),
    visit_aux_data2 varchar(50),
    visit_aux_data3 varchar(50),
    visit_aux_data4 varchar(50),
    user_data varchar(20),
    dtx_name varchar(20),
    age real,
    weight real,
    height real,
    bsa real,
    arm_span real,
    room varchar(20),
    packa_day real,
    pack_years real,
    quit_years real,
    years_smoke real,
    temperature real NOT NULL,
    bar_press real NOT NULL,
    humidity real NOT NULL,
    pre_post smallint NOT NULL,
    occu_expos varchar(60),
    illness varchar(60),
    medication text,
    comments text,
    diagnosis text,
    post_comm text,
    fvl_test boolean NOT NULL,
    svc_test boolean NOT NULL,
    mvv_test boolean NOT NULL,
    frc_test boolean NOT NULL,
    dlco_test boolean NOT NULL,
    pleth_test boolean NOT NULL,
    mip_mep_test boolean NOT NULL,
    static_test boolean NOT NULL,
    dynamic_test boolean NOT NULL,
    sbn2_test boolean NOT NULL,
    nico_test boolean NOT NULL,
    ccm_canopy_test boolean NOT NULL,
    ccm_vent_test boolean NOT NULL,
    ccm_standard_test boolean NOT NULL,
    last_pf_protocol_stage_index smallint NOT NULL,
    published_report bytea,
    pf_consult text,
    blood_test boolean NOT NULL,
    posted boolean NOT NULL,
    posted_date_time timestamp without time zone,
    request_date_time timestamp without time zone,
    testing_stage smallint NOT NULL,
    bmi real NOT NULL,
    qrspt_code varchar(10),
    trend boolean NOT NULL,
    qrspt_lot_number varchar(10),
    bike_test boolean NOT NULL,
    treadmill_test boolean NOT NULL,
    copy_to_query_db boolean NOT NULL,
    tech_guid uuid,
    doctor_guid uuid,
    doctor_guid2 uuid,
    doctor_guid3 uuid,
    site_guid uuid NOT NULL,
    pf_protocol_guid uuid NOT NULL,
    patient_guid uuid NOT NULL,
    ex_fvl_test boolean NOT NULL,
    p100_test boolean NOT NULL,
    lean_body_mass real NOT NULL,
    calibration_date_time timestamp without time zone,
    calibration_workstation_guid uuid,
    graphs bytea,
    study_guid uuid,
    delta_co2_test boolean NOT NULL,
    visit_aux_data5 varchar(50),
    visit_aux_data6 varchar(50),
    visit_aux_data7 varchar(50),
    visit_aux_data8 varchar(50),
    visit_aux_data9 varchar(50),
    visit_aux_data10 varchar(50),
    visit_aux_data11 varchar(50),
    visit_aux_data12 varchar(50),
    visit_aux_data13 varchar(50),
    visit_aux_data14 varchar(50),
    visit_aux_data15 varchar(50),
    visit_aux_data16 varchar(50),
    visit_aux_data17 varchar(50),
    visit_aux_data18 varchar(50),
    visit_aux_data19 varchar(50),
    visit_aux_data20 varchar(50),
    pat_visit_guid uuid NOT NULL,
    report_file_name text,
    order_id varchar(20),
    fot_test boolean NOT NULL,
    strap_raw_test boolean NOT NULL,
    strap_tgv_test boolean NOT NULL,
    pre_fvlats_codes varchar(10),
    pre_dlcoats_codes varchar(10),
    pre_pleth_ats_codes varchar(10),
    pre_frcats_codes varchar(10),
    post_fvlats_codes varchar(10),
    post_dlcoats_codes varchar(10),
    post_pleth_ats_codes varchar(10),
    post_frcats_codes varchar(10),
    export_pending_his boolean NOT NULL,
    export_pending_pdf boolean NOT NULL,
    export_pending_his_this_session boolean NOT NULL,
    export_pending_pdf_this_session boolean NOT NULL,
    export_pending_date timestamp without time zone,
    pred_set_name varchar(50),
    gx_pred_set_name varchar(50),
    ecg_test boolean NOT NULL,
    vendor varchar(50),
    dlco_observed_pred boolean NOT NULL,
    pleth_observed_pred boolean NOT NULL,
    export_pending_text boolean NOT NULL,
    export_pending_text_this_session boolean NOT NULL,
    text_report_file_name text,
    export_pending_text_id smallint NOT NULL,
    pef_test boolean NOT NULL,
    pef_compliance_rate double precision NOT NULL,
    pef_day_to_day_variability double precision NOT NULL,
    pef_total_days integer NOT NULL,
    pef_days_missed integer NOT NULL,
    supports_dlcort boolean NOT NULL,
    web_his boolean NOT NULL,
    web_pdf boolean NOT NULL,
    web_text boolean NOT NULL,
    web_pdf_report_name varchar(60),
    web_text_report_id smallint NOT NULL,
    web_request_date timestamp without time zone,
    export_pending_pdf_report_name varchar(60),
    pending_workstation_guid uuid,
    pre_pdf_report_name text,
    pre_text_report_name text,
    p100_p_fx_test boolean NOT NULL,
    export_pending_cow boolean NOT NULL,
    export_pending_cow_this_session boolean NOT NULL,
    orders text,
    order_visit_i_ds text,
    ccm_face_tent_test boolean NOT NULL,
    review_pending_export boolean NOT NULL,
    export_pending_his_directory text,
    export_pending_pdf_directory text,
    export_pending_text_directory text,
    export_pending_cow_directory text,
    pending_staff_guid uuid,
    visit_aux_data21 varchar(50),
    visit_aux_data22 varchar(50),
    visit_aux_data23 varchar(50),
    visit_aux_data24 varchar(50),
    visit_aux_data25 varchar(50),
    visit_aux_data26 varchar(50),
    visit_aux_data27 varchar(50),
    visit_aux_data28 varchar(50),
    visit_aux_data29 varchar(50),
    visit_aux_data30 varchar(50),
    visit_aux_data31 varchar(50),
    visit_aux_data32 varchar(50),
    visit_aux_data33 varchar(50),
    visit_aux_data34 varchar(50),
    visit_aux_data35 varchar(50),
    visit_aux_data36 varchar(50),
    visit_aux_data37 varchar(50),
    visit_aux_data38 varchar(50),
    visit_aux_data39 varchar(50),
    visit_aux_data40 varchar(50),
    visit_aux_data41 varchar(50),
    visit_aux_data42 varchar(50),
    visit_aux_data43 varchar(50),
    visit_aux_data44 varchar(50),
    visit_aux_data45 varchar(50),
    visit_aux_data46 varchar(50),
    visit_aux_data47 varchar(50),
    visit_aux_data48 varchar(50),
    visit_aux_data49 varchar(50),
    visit_aux_data50 varchar(50),
    visit_aux_data51 varchar(50),
    visit_aux_data52 varchar(50),
    visit_aux_data53 varchar(50),
    visit_aux_data54 varchar(50),
    visit_aux_data55 varchar(50),
    visit_aux_data56 varchar(50),
    visit_aux_data57 varchar(50),
    visit_aux_data58 varchar(50),
    visit_aux_data59 varchar(50),
    visit_aux_data60 varchar(50),
    visit_aux_data61 varchar(50),
    visit_aux_data62 varchar(50),
    visit_aux_data63 varchar(50),
    visit_aux_data64 varchar(50),
    visit_aux_data65 varchar(50),
    visit_aux_data66 varchar(50),
    visit_aux_data67 varchar(50),
    visit_aux_data68 varchar(50),
    visit_aux_data69 varchar(50),
    visit_aux_data70 varchar(50),
    visit_aux_data71 varchar(50),
    visit_aux_data72 varchar(50),
    visit_aux_data73 varchar(50),
    visit_aux_data74 varchar(50),
    visit_aux_data75 varchar(50),
    visit_aux_data76 varchar(50),
    visit_aux_data77 varchar(50),
    visit_aux_data78 varchar(50),
    visit_aux_data79 varchar(50),
    visit_aux_data80 varchar(50),
    visit_aux_data81 varchar(50),
    visit_aux_data82 varchar(50),
    visit_aux_data83 varchar(50),
    visit_aux_data84 varchar(50),
    visit_aux_data85 varchar(50),
    visit_aux_data86 varchar(50),
    visit_aux_data87 varchar(50),
    visit_aux_data88 varchar(50),
    visit_aux_data89 varchar(50),
    visit_aux_data90 varchar(50),
    visit_aux_data91 varchar(50),
    visit_aux_data92 varchar(50),
    visit_aux_data93 varchar(50),
    visit_aux_data94 varchar(50),
    visit_aux_data95 varchar(50),
    visit_aux_data96 varchar(50),
    visit_aux_data97 varchar(50),
    visit_aux_data98 varchar(50),
    visit_aux_data99 varchar(50),
    visit_aux_data100 varchar(50),
    order_procedures text,
    order_modifiers text,
    order_charges text,
    pre_dlcoats_grades varchar(10),
    post_dlcoats_grades varchar(10),
    refresh_orders_request boolean NOT NULL,
    signing_physician_guid uuid,
    signed boolean NOT NULL,
    signed_date_time timestamp without time zone,
    billings_approved boolean NOT NULL,
    billings_approved_date_time timestamp without time zone,
    ideal_body_weight real NOT NULL,
    six_minute_walk_test boolean NOT NULL,
    pre_fvlats_grades varchar(10),
    post_fvlats_grades varchar(10),
    export_pending_cvs boolean NOT NULL,
    export_pending_cvs_this_session boolean NOT NULL,
    export_pending_cvs_directory text,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (pat_visit_id)
);

CREATE TABLE IF NOT EXISTS raw.patient (
    patient_id_num varchar(20) NOT NULL,
    sex_list_id smallint NOT NULL,
    race_list_id smallint NOT NULL,
    patient_last_name varchar(30) NOT NULL,
    patient_first_name varchar(30),
    patient_mid_name varchar(30),
    last_test timestamp without time zone,
    birthday timestamp without time zone,
    user_data varchar(20),
    lock_user varchar(20),
    lock_station varchar(20),
    syringe_flag boolean NOT NULL,
    patient_guid uuid NOT NULL,
    study_guid uuid,
    order_id varchar(20),
    patient_aux_data varchar(50),
    patient_aux_data2 varchar(50),
    patient_aux_data3 varchar(50),
    patient_aux_data4 varchar(50),
    patient_aux_data5 varchar(50),
    patient_aux_data6 varchar(50),
    patient_aux_data7 varchar(50),
    patient_aux_data8 varchar(50),
    patient_aux_data9 varchar(50),
    patient_aux_data10 varchar(50),
    patient_aux_data11 varchar(50),
    patient_aux_data12 varchar(50),
    patient_aux_data13 varchar(50),
    patient_aux_data14 varchar(50),
    patient_aux_data15 varchar(50),
    patient_aux_data16 varchar(50),
    patient_aux_data17 varchar(50),
    patient_aux_data18 varchar(50),
    patient_aux_data19 varchar(50),
    patient_aux_data20 varchar(50),
    last_review_status_id smallint NOT NULL,
    last_vendor varchar(50),
    pef_best_value double precision NOT NULL,
    biologic_flag boolean NOT NULL,
    lock_date_time timestamp without time zone,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (patient_guid)
);

CREATE TABLE IF NOT EXISTS raw.pleth_data (
    pleth_data_id integer NOT NULL,
    pat_visit_id integer NOT NULL,
    effort_type_id smallint NOT NULL,
    effort_time timestamp without time zone NOT NULL,
    effort_cd_us double precision NOT NULL,
    effort_artificial boolean NOT NULL,
    effort_manual boolean NOT NULL,
    pleth_raw_selected boolean NOT NULL,
    pleth_tgv_selected boolean NOT NULL,
    tgv_pleth double precision NOT NULL,
    rv_pleth double precision NOT NULL,
    tlc_pleth double precision NOT NULL,
    rvtlc_pl double precision NOT NULL,
    trapp_gas double precision NOT NULL,
    v_pant double precision NOT NULL,
    raw double precision NOT NULL,
    gaw double precision NOT NULL,
    s_gaw double precision NOT NULL,
    s_raw double precision NOT NULL,
    raw_inspiratory double precision NOT NULL,
    raw_expiratory double precision NOT NULL,
    v_pant_freq double precision NOT NULL,
    pleth_source_type smallint NOT NULL,
    pleth_closed_source_data bytea,
    pleth_open_source_data bytea,
    effort_rp_lp boolean NOT NULL,
    pleth_open_slope double precision NOT NULL,
    pleth_open_offset double precision NOT NULL,
    pleth_closed_slope double precision NOT NULL,
    pleth_closed_offset double precision NOT NULL,
    pleth_open_i_slope double precision NOT NULL,
    pleth_open_i_offset double precision NOT NULL,
    pleth_open_e_slope double precision NOT NULL,
    pleth_open_e_offset double precision NOT NULL,
    pleth_auto_open_slope double precision NOT NULL,
    pleth_auto_open_offset double precision NOT NULL,
    pleth_auto_closed_slope double precision NOT NULL,
    pleth_auto_closed_offset double precision NOT NULL,
    pleth_auto_open_i_slope double precision NOT NULL,
    pleth_auto_open_i_offset double precision NOT NULL,
    pleth_auto_open_e_slope double precision NOT NULL,
    pleth_auto_open_e_offset double precision NOT NULL,
    switch_in_error double precision NOT NULL,
    pleth_ats_codes varchar(10),
    pleth_svc_source_data bytea,
    pf_protocol_stage_index smallint NOT NULL,
    external_resistance double precision NOT NULL,
    box_volume double precision NOT NULL,
    ictlc_pleth double precision NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (pleth_data_id)
);

CREATE TABLE IF NOT EXISTS raw.pred_author (
    pred_author_guid uuid NOT NULL,
    pred_author_name varchar(30) NOT NULL,
    ignore_race boolean NOT NULL,
    units_are_si boolean NOT NULL,
    locked boolean NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (pred_author_guid)
);

CREATE TABLE IF NOT EXISTS raw.pred_options (
    pred_options_id integer NOT NULL,
    pred_set_guid uuid NOT NULL,
    pediatric_age_lower smallint NOT NULL,
    pediatric_age_upper smallint NOT NULL,
    adolescent_age_lower smallint NOT NULL,
    adolescent_age_upper smallint NOT NULL,
    adult_age_lower smallint NOT NULL,
    adult_age_upper smallint NOT NULL,
    force_svcfvc_same boolean NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (pred_options_id)
);

CREATE TABLE IF NOT EXISTS raw.pred_selected_authors (
    params_def_id smallint NOT NULL,
    male_pediatric_guid uuid,
    male_adolescent_guid uuid,
    male_adult_guid uuid,
    female_pediatric_guid uuid,
    female_adolescent_guid uuid,
    female_adult_guid uuid,
    pred_selected_authors_id integer NOT NULL,
    pred_set_guid uuid NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (pred_selected_authors_id)
);

CREATE TABLE IF NOT EXISTS raw.pred_set (
    pred_set_guid uuid NOT NULL,
    pred_set_name varchar(50) NOT NULL,
    disabled boolean NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (pred_set_guid)
);

CREATE TABLE IF NOT EXISTS raw.pred_variable (
    pred_variable_id integer NOT NULL,
    params_def_id smallint NOT NULL,
    pred_variable_type smallint NOT NULL,
    pred_author_guid uuid NOT NULL,
    caucasian_male_pediatric varchar(1000),
    caucasian_male_adolescent varchar(1000),
    caucasian_male_adult varchar(1000),
    caucasian_female_pediatric varchar(1000),
    caucasian_female_adolescent varchar(1000),
    caucasian_female_adult varchar(1000),
    black_male_pediatric varchar(1000),
    black_male_adolescent varchar(1000),
    black_male_adult varchar(1000),
    black_female_pediatric varchar(1000),
    black_female_adolescent varchar(1000),
    black_female_adult varchar(1000),
    hispanic_male_pediatric varchar(1000),
    hispanic_male_adolescent varchar(1000),
    hispanic_male_adult varchar(1000),
    hispanic_female_pediatric varchar(1000),
    hispanic_female_adolescent varchar(1000),
    hispanic_female_adult varchar(1000),
    asian_male_pediatric varchar(1000),
    asian_male_adolescent varchar(1000),
    asian_male_adult varchar(1000),
    asian_female_pediatric varchar(1000),
    asian_female_adolescent varchar(1000),
    asian_female_adult varchar(1000),
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (pred_variable_id)
);

CREATE TABLE IF NOT EXISTS raw.race_correction (
    params_def_id smallint NOT NULL,
    caucasian double precision NOT NULL,
    black double precision NOT NULL,
    hispanic double precision NOT NULL,
    asian double precision NOT NULL,
    race_correction_id integer NOT NULL,
    pred_set_guid uuid NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (race_correction_id)
);

CREATE TABLE IF NOT EXISTS raw.review_status (
    review_status_id smallint NOT NULL,
    review_status_desc varchar(30) NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (review_status_id)
);

CREATE TABLE IF NOT EXISTS raw.sbn2_data (
    sbn2_data_id integer NOT NULL,
    pat_visit_id integer NOT NULL,
    effort_type_id smallint NOT NULL,
    effort_time timestamp without time zone NOT NULL,
    effort_cd_us double precision NOT NULL,
    effort_artificial boolean NOT NULL,
    effort_manual boolean NOT NULL,
    effort_selected boolean NOT NULL,
    cv double precision NOT NULL,
    cc double precision NOT NULL,
    d_phase3 double precision NOT NULL,
    cvvc double precision NOT NULL,
    cctlc double precision NOT NULL,
    ccfrc double precision NOT NULL,
    n27501250 double precision NOT NULL,
    v_dan_sbn2 double precision NOT NULL,
    tlcsbn2 double precision NOT NULL,
    svcsbn2 double precision NOT NULL,
    sbn2_source_data bytea,
    effort_rp_lp boolean NOT NULL,
    pf_protocol_stage_index smallint NOT NULL,
    icsbn2 double precision NOT NULL,
    sbn2_svc_source_data bytea,
    external_deadspace double precision NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (sbn2_data_id)
);

CREATE TABLE IF NOT EXISTS raw.svc_data (
    svc_data_id integer NOT NULL,
    pat_visit_id integer NOT NULL,
    effort_type_id smallint NOT NULL,
    effort_time timestamp without time zone NOT NULL,
    effort_cd_us double precision NOT NULL,
    effort_artificial boolean NOT NULL,
    effort_manual boolean NOT NULL,
    effort_selected boolean NOT NULL,
    vcsvc double precision NOT NULL,
    icsvc double precision NOT NULL,
    ervsvc double precision NOT NULL,
    auto_icsvc double precision NOT NULL,
    svc_source_data bytea,
    svc_source_test_type smallint NOT NULL,
    pf_protocol_stage_index smallint NOT NULL,
    effort_rp_lp boolean NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (svc_data_id)
);

CREATE TABLE IF NOT EXISTS raw.site (
    site_name varchar(80) NOT NULL,
    site_division varchar(80),
    site_address varchar(30),
    site_city varchar(30),
    site_state varchar(4),
    site_zip_code varchar(10),
    site_country varchar(30),
    site_telephone1 varchar(14),
    site_telephone2 varchar(14),
    site_fax varchar(14),
    site_e_mail varchar(30),
    site_guid uuid NOT NULL,
    ccow_user_suffix varchar(80),
    ccow_patient_suffix varchar(80),
    ccow_encounter_suffix varchar(80),
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (site_guid)
);

CREATE TABLE IF NOT EXISTS raw.six_minute_walk_data (
    six_minute_walk_data_id integer NOT NULL,
    pat_visit_id integer NOT NULL,
    effort_type_id smallint NOT NULL,
    effort_time timestamp without time zone NOT NULL,
    effort_cd_us double precision NOT NULL,
    effort_artificial boolean NOT NULL,
    effort_manual boolean NOT NULL,
    effort_selected boolean NOT NULL,
    effort_rp_lp boolean NOT NULL,
    pf_protocol_stage_index smallint NOT NULL,
    distance_walked double precision NOT NULL,
    sp_o2 double precision NOT NULL,
    hr double precision NOT NULL,
    paused_time double precision NOT NULL,
    numberof_pauses double precision NOT NULL,
    start_exercise_time smallint NOT NULL,
    start_recovery_time smallint NOT NULL,
    exercise_time_in_min smallint NOT NULL,
    source_data bytea,
    manually_entered_data bytea,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (six_minute_walk_data_id)
);

CREATE TABLE IF NOT EXISTS raw.staff (
    staff_guid uuid NOT NULL,
    staff_id_num varchar(20) NOT NULL,
    staff_last_name varchar(30) NOT NULL,
    staff_first_name varchar(20),
    staff_login varchar(20),
    staff_password bytea,
    staff_deleted boolean NOT NULL,
    type smallint NOT NULL,
    role_guid uuid,
    review_station_config bytea,
    staff_es_active boolean NOT NULL,
    staff_proxy bytea,
    pf_interp_type_id smallint NOT NULL,
    ex_interp_type_id smallint NOT NULL,
    pf_custom_consult_guid uuid,
    ex_custom_consult_guid uuid,
    pf_standard_consult_guid uuid,
    ex_standard_consult_guid uuid,
    nbg_standard_consult_guid uuid,
    staff_profile_name varchar(30),
    review_only boolean NOT NULL,
    use_filters boolean NOT NULL,
    can_override_filter boolean NOT NULL,
    physician_type_filter smallint NOT NULL,
    physician_guid_filter uuid,
    technician_guid_filter uuid,
    site_guid_filter uuid,
    review_status_filter smallint NOT NULL,
    is_user boolean NOT NULL,
    password_locked boolean NOT NULL,
    first_time_password boolean NOT NULL,
    is_emergency boolean NOT NULL,
    emergency_count integer NOT NULL,
    password_date timestamp without time zone,
    staff_expiration_date timestamp without time zone,
    include_no_visit_filter boolean NOT NULL,
    exclude_syringe_patients_filter boolean NOT NULL,
    exclude_biologic_patients_filter boolean NOT NULL,
    use_order_filters boolean NOT NULL,
    new_orders_filter boolean NOT NULL,
    assigned_orders_filter boolean NOT NULL,
    completed_orders_filter boolean NOT NULL,
    canceled_orders_filter boolean NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (staff_guid)
);

CREATE TABLE IF NOT EXISTS raw.static_data (
    static_data_id integer NOT NULL,
    pat_visit_id integer NOT NULL,
    effort_type_id smallint NOT NULL,
    effort_time timestamp without time zone NOT NULL,
    effort_cd_us double precision NOT NULL,
    effort_artificial boolean NOT NULL,
    effort_manual boolean NOT NULL,
    ptp_max double precision NOT NULL,
    ptp_max_vol double precision NOT NULL,
    ptp90_tlc double precision NOT NULL,
    ptp80_tlc double precision NOT NULL,
    ptp70_tlc double precision NOT NULL,
    ptp60_tlc double precision NOT NULL,
    ptp50_tlc double precision NOT NULL,
    ptp40_tlc double precision NOT NULL,
    ptp30_tlc double precision NOT NULL,
    ptp20_tlc double precision NOT NULL,
    ptp_frc double precision NOT NULL,
    tlc_st double precision NOT NULL,
    co_eff_retr double precision NOT NULL,
    cst_i double precision NOT NULL,
    cst_e double precision NOT NULL,
    sp_cst_i double precision NOT NULL,
    sp_cst_e double precision NOT NULL,
    static_source_data bytea,
    pf_protocol_stage_index smallint NOT NULL,
    i_select boolean NOT NULL,
    e_select boolean NOT NULL,
    recoil_select boolean NOT NULL,
    ptp90_pred_tlc double precision NOT NULL,
    ptp80_pred_tlc double precision NOT NULL,
    ptp70_pred_tlc double precision NOT NULL,
    ptp60_pred_tlc double precision NOT NULL,
    ptp50_pred_tlc double precision NOT NULL,
    ptp40_pred_tlc double precision NOT NULL,
    ptp30_pred_tlc double precision NOT NULL,
    ptp20_pred_tlc double precision NOT NULL,
    ic_st double precision NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (static_data_id)
);

CREATE TABLE IF NOT EXISTS raw.test_type (
    test_type_id integer NOT NULL,
    test_type_desc varchar(50) NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (test_type_id)
);

CREATE TABLE IF NOT EXISTS raw.workstation (
    workstation_name varchar(50) NOT NULL,
    last_report integer NOT NULL,
    workstation_user_name varchar(20),
    work_station_active boolean NOT NULL,
    program_run varchar(30),
    workstation_external_resistance double precision NOT NULL,
    workstation_external_dead_space double precision NOT NULL,
    hardware_id smallint NOT NULL,
    workstation_bike_id integer,
    workstation_treadmill_id integer,
    workstation_hr_monitor_id integer,
    workstation_pulse_oximeter_id integer,
    workstation_bp_cuff_id integer,
    workstation_ecgid integer,
    site_guid uuid NOT NULL,
    workstation_guid uuid NOT NULL,
    com_port smallint NOT NULL,
    auto_logout_time smallint NOT NULL,
    weatherman_type smallint NOT NULL,
    com_port_weatherman smallint NOT NULL,
    com_port_bike smallint NOT NULL,
    com_port_treadmill smallint NOT NULL,
    com_port_hr_monitor smallint NOT NULL,
    com_port_pulse_oximeter smallint NOT NULL,
    com_port_bp_cuff smallint NOT NULL,
    com_port_ecg smallint NOT NULL,
    syringe_dead_space double precision NOT NULL,
    n2_wash_corr_factor_human double precision NOT NULL,
    n2_wash_corr_factor_syringe double precision NOT NULL,
    gx_dry_cartridge boolean NOT NULL,
    bike_min_watts double precision NOT NULL,
    bike_max_watts double precision NOT NULL,
    bike_watts_per_volt double precision NOT NULL,
    t_mill_min_speed double precision NOT NULL,
    t_mill_max_speed double precision NOT NULL,
    t_mill_min_grade double precision NOT NULL,
    t_mill_max_grade double precision NOT NULL,
    workstation_core_body_temperature_id integer,
    workstation_body_sweat_id integer,
    workstation_transcutaneous_co2_id integer,
    com_io_port_hr_monitor smallint NOT NULL,
    com_io_port_pulse_oximeter smallint NOT NULL,
    com_io_port_bike_watts smallint NOT NULL,
    com_io_port_bike_rpm smallint NOT NULL,
    com_io_port_t_mill_speed smallint NOT NULL,
    com_io_port_t_mill_grade smallint NOT NULL,
    com_io_port_core_body_temperature smallint NOT NULL,
    com_io_port_body_sweat smallint NOT NULL,
    com_io_port_transcutaneous_co2 smallint NOT NULL,
    workstation_distal_dead_space double precision NOT NULL,
    _snapshot_id bigint,
    _load_id bigint,
    _loaded_at timestamp without time zone NOT NULL DEFAULT now(),
    _source_row_hash text,
    PRIMARY KEY (workstation_guid)
);

-- Índices sobre columnas relacionales detectadas como FK en SQL Server.
CREATE INDEX IF NOT EXISTS idx_raw_blood_data_effort_type_id
    ON raw.blood_data (effort_type_id);

CREATE INDEX IF NOT EXISTS idx_raw_blood_data_pat_visit_id
    ON raw.blood_data (pat_visit_id);

CREATE INDEX IF NOT EXISTS idx_raw_dlco_data_effort_type_id
    ON raw.dlco_data (effort_type_id);

CREATE INDEX IF NOT EXISTS idx_raw_dlco_data_pat_visit_id
    ON raw.dlco_data (pat_visit_id);

CREATE INDEX IF NOT EXISTS idx_raw_delta_co2_data_effort_type_id
    ON raw.delta_co2_data (effort_type_id);

CREATE INDEX IF NOT EXISTS idx_raw_delta_co2_data_pat_visit_id
    ON raw.delta_co2_data (pat_visit_id);

CREATE INDEX IF NOT EXISTS idx_raw_dynamic_data_effort_type_id
    ON raw.dynamic_data (effort_type_id);

CREATE INDEX IF NOT EXISTS idx_raw_dynamic_data_pat_visit_id
    ON raw.dynamic_data (pat_visit_id);

CREATE INDEX IF NOT EXISTS idx_raw_fot_data_effort_type_id
    ON raw.fot_data (effort_type_id);

CREATE INDEX IF NOT EXISTS idx_raw_fot_data_pat_visit_id
    ON raw.fot_data (pat_visit_id);

CREATE INDEX IF NOT EXISTS idx_raw_frc_data_effort_type_id
    ON raw.frc_data (effort_type_id);

CREATE INDEX IF NOT EXISTS idx_raw_frc_data_pat_visit_id
    ON raw.frc_data (pat_visit_id);

CREATE INDEX IF NOT EXISTS idx_raw_fvl_data_effort_type_id
    ON raw.fvl_data (effort_type_id);

CREATE INDEX IF NOT EXISTS idx_raw_fvl_data_pat_visit_id
    ON raw.fvl_data (pat_visit_id);

CREATE INDEX IF NOT EXISTS idx_raw_mvv_data_effort_type_id
    ON raw.mvv_data (effort_type_id);

CREATE INDEX IF NOT EXISTS idx_raw_mvv_data_pat_visit_id
    ON raw.mvv_data (pat_visit_id);

CREATE INDEX IF NOT EXISTS idx_raw_mip_data_effort_type_id
    ON raw.mip_data (effort_type_id);

CREATE INDEX IF NOT EXISTS idx_raw_mip_data_pat_visit_id
    ON raw.mip_data (pat_visit_id);

CREATE INDEX IF NOT EXISTS idx_raw_p100_data_effort_type_id
    ON raw.p100_data (effort_type_id);

CREATE INDEX IF NOT EXISTS idx_raw_p100_data_pat_visit_id
    ON raw.p100_data (pat_visit_id);

CREATE INDEX IF NOT EXISTS idx_raw_pf_protocol_challenge_agent_id
    ON raw.pf_protocol (challenge_agent_id);

CREATE INDEX IF NOT EXISTS idx_raw_pf_protocol_stage_pf_protocol_guid
    ON raw.pf_protocol_stage (pf_protocol_guid);

CREATE INDEX IF NOT EXISTS idx_raw_pat_visit_doctor_guid
    ON raw.pat_visit (doctor_guid);

CREATE INDEX IF NOT EXISTS idx_raw_pat_visit_doctor_guid2
    ON raw.pat_visit (doctor_guid2);

CREATE INDEX IF NOT EXISTS idx_raw_pat_visit_doctor_guid3
    ON raw.pat_visit (doctor_guid3);

CREATE INDEX IF NOT EXISTS idx_raw_pat_visit_pf_protocol_guid
    ON raw.pat_visit (pf_protocol_guid);

CREATE INDEX IF NOT EXISTS idx_raw_pat_visit_patient_guid
    ON raw.pat_visit (patient_guid);

CREATE INDEX IF NOT EXISTS idx_raw_pat_visit_review_status_id
    ON raw.pat_visit (review_status_id);

CREATE INDEX IF NOT EXISTS idx_raw_pat_visit_site_guid
    ON raw.pat_visit (site_guid);

CREATE INDEX IF NOT EXISTS idx_raw_pat_visit_tech_guid
    ON raw.pat_visit (tech_guid);

CREATE INDEX IF NOT EXISTS idx_raw_pleth_data_effort_type_id
    ON raw.pleth_data (effort_type_id);

CREATE INDEX IF NOT EXISTS idx_raw_pleth_data_pat_visit_id
    ON raw.pleth_data (pat_visit_id);

CREATE INDEX IF NOT EXISTS idx_raw_pred_options_pred_set_guid
    ON raw.pred_options (pred_set_guid);

CREATE INDEX IF NOT EXISTS idx_raw_pred_selected_authors_pred_set_guid
    ON raw.pred_selected_authors (pred_set_guid);

CREATE INDEX IF NOT EXISTS idx_raw_pred_variable_pred_author_guid
    ON raw.pred_variable (pred_author_guid);

CREATE INDEX IF NOT EXISTS idx_raw_race_correction_pred_set_guid
    ON raw.race_correction (pred_set_guid);

CREATE INDEX IF NOT EXISTS idx_raw_sbn2_data_effort_type_id
    ON raw.sbn2_data (effort_type_id);

CREATE INDEX IF NOT EXISTS idx_raw_sbn2_data_pat_visit_id
    ON raw.sbn2_data (pat_visit_id);

CREATE INDEX IF NOT EXISTS idx_raw_svc_data_effort_type_id
    ON raw.svc_data (effort_type_id);

CREATE INDEX IF NOT EXISTS idx_raw_svc_data_pat_visit_id
    ON raw.svc_data (pat_visit_id);

CREATE INDEX IF NOT EXISTS idx_raw_six_minute_walk_data_pat_visit_id
    ON raw.six_minute_walk_data (pat_visit_id);

CREATE INDEX IF NOT EXISTS idx_raw_staff_role_guid
    ON raw.staff (role_guid);

CREATE INDEX IF NOT EXISTS idx_raw_static_data_effort_type_id
    ON raw.static_data (effort_type_id);

CREATE INDEX IF NOT EXISTS idx_raw_static_data_pat_visit_id
    ON raw.static_data (pat_visit_id);

CREATE INDEX IF NOT EXISTS idx_raw_workstation_hardware_id
    ON raw.workstation (hardware_id);

CREATE INDEX IF NOT EXISTS idx_raw_workstation_site_guid
    ON raw.workstation (site_guid);

CREATE INDEX IF NOT EXISTS idx_raw_workstation_workstation_bp_cuff_id
    ON raw.workstation (workstation_bp_cuff_id);

CREATE INDEX IF NOT EXISTS idx_raw_workstation_workstation_bike_id
    ON raw.workstation (workstation_bike_id);

CREATE INDEX IF NOT EXISTS idx_raw_workstation_workstation_hr_monitor_id
    ON raw.workstation (workstation_hr_monitor_id);

CREATE INDEX IF NOT EXISTS idx_raw_workstation_workstation_pulse_oximeter_id
    ON raw.workstation (workstation_pulse_oximeter_id);

CREATE INDEX IF NOT EXISTS idx_raw_workstation_workstation_treadmill_id
    ON raw.workstation (workstation_treadmill_id);
